server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ma_project
    username: root
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8085
  profiles:
    active: default

  aop:
    auto: true
    proxy-target-class: true


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  # Circuit Breaker
  circuitbreaker:
    instances:
      paymentRideBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50 #in %
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  # Rate Limiter
  ratelimiter:
    instances:
      userServiceRateLimiter:
        limit-for-period: 10 # Max requests per refresh period
        limit-refresh-period: 1s # Reset limit every 1 second
        timeout-duration: 100ms # Max wait time for a permit
        register-health-indicator: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springdoc: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.retry: TRACE
    org.springframework.cloud: DEBUG
    orm:
      connections:
        pooling: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
